### ISSUE TITLE
openrestry-luajit android

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake-repo#1148]
### Is your feature request related to a problem? Please describe.

openrestry-luajit doesn't build on android because it requires running a lua program, the build script uses the target toolchain but the lua program needs to run on the host machine.

https://github.com/openresty/luajit2/issues/156#issuecomment-1090730196

### Describe the solution you'd like

Don't build minilua and run a local lua install.

**Comment by waruqi** [comment]
you can refer the luajit script in xmake-repo. https://github.com/xmake-io/xmake-repo/blob/20363ebe0a2f9cef8da1a311928dffd36b84f3b6/packages/l/luajit/port/xmake.lua#L123-L127

it will build and run lua program on host machine, and it works for android.

**Comment by waruqi** [comment]
I saw your ci job, it works for android. 

luajit only support android/arm64-v8a, does not support armv7 on ci, because it need build buildvm/minilua for 32bits host platform (-m32).

But ubuntu does not provide i386 devel libs and headers on ci. If you want to build luajit for android armv7, you need install i386 libs on ubuntu x84_64.

So you can open android platform, and I will ignore armv7 errors and merge it.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/151335/162223384-9bfc64ee-b675-4ae4-b083-0b0793ac9745.png">
